CC=gcc
CFLAGS= -g -Wall -Wpedantic 

SCAT_VER_DEF = "-DSCAT_VER=\"Build 202502231824\""

exec_out=bin\scat.exe

LD=gcc
LDFLAGS= 
LDLIBS=

sources := src\int_math_utils.c src\options.c src\os_utils.c src\slow_cat.c
obj_files := $(patsubst src\\%.c,obj\\%.o,$(sources))

all: bin obj $(exec_out)

$(exec_out): $(obj_files)
	$(LD) $(LDFLAGS) -o $@ $^ $(LDLIBS)

obj\\%.o: src\\%.c
	$(CC) $(CFLAGS) $(SCAT_VER_DEF) -c -o $@ $<

obj:
	mkdir $@

bin:
	mkdir $@

clean_obj\\%.o:
	-del $(patsubst clean_%,%,$@)

clean_obj: $(patsubst obj\\%.o,clean_obj\\%.o,$(obj_files))
	-rmdir $(patsubst clean_%,%,$@)

clean_$(exec_out):
	-del $(exec_out)

clean_bin: clean_$(exec_out)
	-rmdir $(patsubst clean_%,%,$@)

clean: clean_bin clean_obj
